INSERT INTO GENRES VALUES (0, 'Non fiction');
INSERT INTO AUTHORS VALUES (0, 'Arkady and Boris Strugatsky');
INSERT INTO BOOKS VALUES (0, 'The Doomed City');
INSERT INTO BOOKS_AUTHORS VALUES (0, 0);
INSERT INTO BOOKS_GENRES VALUES (0, 0);
INSERT INTO BOOKS_AUTHORS VALUES (1, 0);
INSERT INTO BOOKS_GENRES VALUES (1, 0);