INSERT INTO PERSONS VALUES (3, 29, '1989-11-17', 17, 10, 'Vadoniy', 1989);

INSERT INTO CLIENTS VALUES (1, 'Moscow, Kirovogradskaya street, 2k1, 361', 'Entrance 3, call 350 (concierge)', 'kurbatov_1989@inbox.ru', 0, '+79263368886', '2019-03-16', 3);

INSERT INTO INGREDIENTS VALUES (1, 'Topper for pizza', 'kg', 'Parmesan', 3.0, 'FILLING');
INSERT INTO INGREDIENTS VALUES (2, 'Topper for pizza', 'kg', 'Mozzarella', 1.5, 'FILLING');
INSERT INTO INGREDIENTS VALUES (3, 'Tasty sausage', 'kg', 'Sausage', 3.5, 'FILLING');
INSERT INTO INGREDIENTS VALUES (4, 'Spread it on dough', 'Litres', 'Tomato paste', 7, 'FILLING');
INSERT INTO INGREDIENTS VALUES (5, 'White powder =)', 'kg', 'Flour', 5.0, 'DOUGH');
INSERT INTO INGREDIENTS VALUES (6, 'Eggs', 'units', 'Eggs', 200, 'DOUGH');

INSERT INTO PIZZAS VALUES (1, 'Cheese pizza');
INSERT INTO PIZZAS VALUES (2, 'BBQ pizza');

--id/rate/ing/pizz
--INSERT INTO INGREDIENTSRATE VALUES (0.3, 5, 1);
--INSERT INTO INGREDIENTSRATE VALUES (2.0, 6, 1);
--INSERT INTO INGREDIENTSRATE VALUES (0.1, 4, 1);
--INSERT INTO INGREDIENTSRATE VALUES (0.2, 2, 1);
--INSERT INTO INGREDIENTSRATE VALUES (0.3, 5, 2);
--INSERT INTO INGREDIENTSRATE VALUES (2.0, 6, 2);
--INSERT INTO INGREDIENTSRATE VALUES (0.1, 4, 2);
--INSERT INTO INGREDIENTSRATE VALUES (0.2, 2, 2);
--INSERT INTO INGREDIENTSRATE VALUES (0.2, 3, 2);

--id/rate/ing/pizz
INSERT INTO INGREDIENTSRATE VALUES (1, 0.3, 5, 1);
INSERT INTO INGREDIENTSRATE VALUES (2, 2.0, 6, 1);
INSERT INTO INGREDIENTSRATE VALUES (3, 0.1, 4, 1);
INSERT INTO INGREDIENTSRATE VALUES (4, 0.2, 2, 1);
INSERT INTO INGREDIENTSRATE VALUES (5, 0.3, 5, 2);
INSERT INTO INGREDIENTSRATE VALUES (6, 2.0, 6, 2);
INSERT INTO INGREDIENTSRATE VALUES (7, 0.1, 4, 2);
INSERT INTO INGREDIENTSRATE VALUES (8, 0.2, 2, 2);
INSERT INTO INGREDIENTSRATE VALUES (9, 0.2, 3, 2);